### PR TITLE
:bug: Fix throw by close

### LINKED ISSUE #46: [Bug] Throw & Drop
[Bug] Throw & Drop

### PR DESCRIPTION
**Pull request by SettingDust**
close #46

### CODE REVIEW

File: src/main/java/team/ebi/epicbanitem/check/listener/InventoryListener.java [hunk 1]
```diff
@@ -85,29 +86,80 @@ private static ItemStack getItem(DataContainer view, int quantity) {
...
+                            entity.offer(Keys.REPRESENTED_ITEM, optionalItemStack.get().createSnapshot());
+                        } else {
+                            return true;
+                        }
+                    }
+                }
+                return false;
+            }
+        );
+    }
```
Comment (ginyai) [inline src/main/java/team/ebi/epicbanitem/check/listener/InventoryListener.java]: Info?

File: src/main/java/team/ebi/epicbanitem/check/listener/InventoryListener.java [hunk 2]
```diff
@@ -85,29 +86,80 @@ private static ItemStack getItem(DataContainer view, int quantity) {
...
+        Stream
+            .concat(Stream.of(cursorTransaction), transactions.stream())
+            .forEach(
+                transaction -> {
+                    ItemStackSnapshot item = transaction.getOriginal();
+                    CheckResult result = service.check(item, player.getWorld(), Triggers.THROW, player);
+                    if (result.isBanned()) {
+                        event.setCancelled(true);
+                        Optional<ItemStack> optionalFinalItem = result.getFinalView().map(view -> getItem(view, item.getQuantity()));
+                        optionalFinalItem.ifPresent(finalItem -> transaction.setCustom(finalItem.createSnapshot()));
```
Comment (ginyai) [inline src/main/java/team/ebi/epicbanitem/check/listener/InventoryListener.java]: Will the `setCustom` have effects when the event is cancelled?
